### ISSUE TITLE
Перевести документацию на английский

### ISSUE THREAD

**Issue by SilverFire** [LAV45/yii2-translated-behavior#1]
Так как в сообщество у Yii не ограничено рускоговорящими, было бы неплохо перевести документацию на Английский. Так вашим расширением с большей вероятностью смогут воспользоваться и англоязычные программисты.

**Comment by LAV45** [comment]
ОК, согласен.

**Comment by LAV45** [comment]
https://github.com/LAV45/yii2-translated-behavior/commit/5b352db6786c5e5472d4bbc9088eecf8220f3c5f
