### ISSUE TITLE
Change lang table character set to utf8mb4

### ISSUE THREAD

**Issue by athl64** [lav45/yii2-translated-behavior#10]
Because mysql utf8 is not fully support standard ( [StackOverflow description](https://stackoverflow.com/a/30074553) ) - i propose to change the initial character set in migration to **utf8mb4** and collation to **utf8mb4_unicode_ci** at this line [migration code](https://github.com/lav45/yii2-translated-behavior/blob/master/migrate/m151220_112320_lang.php#L15)
Or, maybe there is a reason why current collation used at now?

Thanks.

**Comment by lav45** [comment]
Thanks for the addition!
Added in https://github.com/lav45/yii2-translated-behavior/commit/8136c6a66b6bb89ba8f0df621477e76447b85de8
