### ISSUE TITLE
It is not being written for other languages in a default language

### ISSUE THREAD

**Issue by AlisherN** [lav45/yii2-translated-behavior#11]
I've installed the extension as showed in the instruction. It is working well when I create record in a language that is not default one(I updated the record successfully for non-default languages). However, When I'm trying to update a record created in default language for non-default ones, it shows a record created in the default language. I hope you will give a solution. Thanks in advance.

**Comment by lav45** [comment]
You can provide an example code to reproduce this issue?

**Comment by AlisherN** [comment]
When I create new record with non-default language, it will be saved and then I can update(if it doesn't exist, can create) the record related to this one for other languages. But, If I create new record in default language(i.e in English), then I can't update the record related this one in other languages.
For example:
Default language is English.
First I've created a record in Russian that is non-default language:
![image](https://user-images.githubusercontent.com/26760588/47559757-c402ac80-d92f-11e8-920e-d1b7d5b4e5f0.png)

In this case, I can update the record for other languages:
![image](https://user-images.githubusercontent.com/26760588/47559889-2cea2480-d930-11e8-9ecf-2c5a14853e21.png)

However, If I create a record in default language(in English), I can't update the record in other languages:
![image](https://user-images.githubusercontent.com/26760588/47560074-a550e580-d930-11e8-8eb7-53175e1cc31f.png)

![image](https://user-images.githubusercontent.com/26760588/47560122-cf0a0c80-d930-11e8-96e1-7d545c0440fc.png)

Here are my example codes:
**TestOne model**:

```
<?php
namespace common\models;
use Yii;

use lav45\translate\TranslatedTrait;
use lav45\translate\TranslatedBehavior;

class TestOne extends \yii\db\ActiveRecord
{
    use TranslatedTrait;

    public static function tableName()
    {
        return 'TestOne';
    }
    public function rules()
    {
        return [
            [['name'], 'required'],
            [['description', 'full_desc'], 'string'],
            [['name'], 'string', 'max' => 255],
        ];
    }
    public function behaviors()
    {
        return [
            [
                'class' => TranslatedBehavior::className(),
                'translateRelation' => 'testOneTranslate',
                'translateAttributes' => [
                    'name',
                    'description',
                    'full_desc',
                ]
            ]
        ];
    }

    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'name' => Yii::t('app', 'Name'),
            'description' => Yii::t('app', 'Description'),
            'full_desc' => Yii::t('app', 'Full Desc'),
        ];
    }
    public function getTestOneTranslate()
    {
        return $this->hasMany(TestOneTranslate::className(), ['t_id' => 'id']);
    }
}
```

**TestOneTranslate** model:
```
<?php
namespace common\models;
use Yii;

class TestOneTranslate extends \yii\db\ActiveRecord
{

    public static function tableName()
    {
        return 'TestOneTranslate';
    }

    public function rules()
    {
        return [
            [['t_id', 'lang_id', 'name'], 'required'],
            [['t_id'], 'integer'],
            [['description', 'full_desc'], 'string'],
            [['lang_id'], 'string', 'max' => 2],
            [['name'], 'string', 'max' => 255],
        ];
    }

    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            't_id' => Yii::t('app', 'T ID'),
            'lang_id' => Yii::t('app', 'Lang ID'),
            'name' => Yii::t('app', 'Name'),
            'description' => Yii::t('app', 'Description'),
            'full_desc' => Yii::t('app', 'Full Desc'),
        ];
    }
}
```

**TestOneController.php** :

```
<?php
namespace backend\controllers;
use Yii;
use common\models\TestOne;
use backend\models\TestOneSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;


use lav45\translate\models\Lang;
use yii\data\ActiveDataProvider;

class TestOneController extends Controller
{
  // ...
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => TestOne::find()
                ->with([
                    'currentTranslate', // loadabing data associated with the current translation
                    'hasTranslate' // need to display the status was translated page
                ]),
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
            'langList' => Lang::getList(),
        ]);
    }
// ...
    public function actionCreate()
    {
        $model = new TestOne();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['index']);
        }
        return $this->render('create', [
            'model' => $model,
        ]);
    }

    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['index']);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }
// ...
}
```

**index.php view**:

```
<?php
use yii\helpers\Html;
use yii\grid\GridView;

$this->title = Yii::t('app', 'Test Ones');
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="test-one-index">

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'columns' => [
            'name',
            'description',
            [
                'class' => 'lav45\translate\grid\ActionColumn',
                'languages' => $langList,
            ],
            [
                'class' => 'yii\grid\ActionColumn',
                'template' => '{delete}'
            ],
        ],
    ]);
    ?>

</div>
```

**Comment by lav45** [comment]
`ActionColumn` формирует ссылку с параметром $_GET['lang_id'] 
https://github.com/lav45/yii2-translated-behavior/blob/master/src/grid/ActionColumn.php#L39
При переходе на страницу для перевода ото параметр передается `lav45\translate\TranslatedBehavior`
https://github.com/lav45/yii2-translated-behavior-demo/blob/master/backend/config/bootstrap.php#L52-L54
Но в твоем случае параметр `lang_id` является частью ссылки и он уже не подхватывается не передается `lav45\translate\TranslatedBehavior`

С помощью передачи языка через `Yii::$container->set()` ты отвязываешь язык админки от переводимых данных. Т.е. в форме может отображаться текст перевода, но ошибки, отображаемые при проверки данных, всегда будут отображаться на базовом языке (en)

Если ты все таки хочешь использовать язык как часть url и менять перевод не только данных но и всего содержимого страницы тогда тебе нужно подключить `yii\filters\ContentNegotiator`
https://github.com/lav45/yii2-translated-behavior-demo/blob/master/frontend/controllers/SiteController.php#L23
и заменить ContentNegotiator::$languageParam = 'lang_id';
https://github.com/yiisoft/yii2/blob/master/framework/filters/ContentNegotiator.php#L103
