### ISSUE TITLE
Язык по умолчанию без приставки

### ISSUE THREAD

**Issue by la5erdance** [lav45/yii2-translated-behavior#12]
Можно ли сделать так что язык по умолчанию был без приставки, например https://domain.com/ru/page выходит, но хотелось бы https://domain.com/page, если русский у нас по умолчанию?

**Comment by lav45** [comment]
В URL-ах обычно используются обязательные параметры. Если язык не является обязательным тога его лучше передавать как обычный GET параметр
https://domain.com/page
https://domain.com/page?lang=en

```
class PageController extends Controller
{
    public function actionIndex($lang='ru')
    {
        // ...
    }
}
```
