### ISSUE TITLE
Translated slugs

### ISSUE THREAD

**Issue by nedarta** [lav45/yii2-translated-behavior#13]
Hi. First of all - your extension ir great. I use it my projects quite often. Works (almoast) out the box.

My questions:
- I would like to use translated slugs (en/about-us; ru/o-nas). My first thought was that I just mark slug as translateable row (Which should be translated). Now I'm stuck. Is there a good "how to" recipe?
- Is there any good/easy way to create an ActiveRecord with multiple languages simultaneously? For example tabed input form, where I can fill up the data in my defined languages?
Thanks in advance!

**Comment by lav45** [comment]
If I understand you correctly then you need to do this
```php
public function actionView($_lang, $slug)
{
    // old vervion
    // $post = Post::findOne(['slug' => $slug]);

    $postLang = PostLang::findOne([
        'lang' => $_lang,
        'slug' => $slug
    ]);

    $post = $postLang->post;
    ...
}
```

**Comment by nedarta** [comment]
Thanks. You got the idea: I needed "translated slugs". I guess it makes more sense than all languages it's the same (only language code changes). Looks fine. I'll try it and leave some feedback here.

Anyway - I think that I'm not the only one who was/is curious about this. SEO, you know... Thank you.
