### ISSUE TITLE
Translated slugs and language swith

### ISSUE THREAD

**Issue by nedarta** [LAV45/yii2-translated-behavior#16]
Previous issue I wrote about translated slug. Works fine: 

    public function actionView($_lang, $slug)
    {
        $portfolioLang = PortfolioLang::findOne(['lang_id' => $_lang, 'slug' => $slug]);
	$model = $portfolioLang->portfolio;	
	$pictures = PortfolioPicture::find()->where(['portfolio_id' => $model->id])->orderBy(['sorting'=>SORT_ASC])->all();       

        return $this->render('view', [
            'model' => $model,
            'picture' => $pictures,
            'langList' => Lang::getList(),
        ]);
    }

The problem is - I can't imagine how to switch languages between these slugs. Instead of desired url "ru/nazvanie" I get "ru/title". I'm using a little bit modified https://github.com/lav45/yii2-translated-behavior-demo/blob/master/frontend/components/LangHelper.php. Any hints how to modify this class?

Asked this in Stackoverflow but without any luck.

 Thanks

**Comment by lav45** [comment]
https://github.com/lav45/yii2-translated-behavior-demo/blob/master/frontend/components/LangHelper.php#L85

```php
Url::toRoute([Yii::$app->getHomeUrl(), $this->langAttribute => $lang_id]);
// rewrite to =>
$page = ['/page/view', 'slug' => 'main'];
$page[$this->langAttribute] = $lang_id;
Url::toRoute($page);
```
