### ISSUE TITLE
Class 'Locale' not found

### ISSUE THREAD

**Issue by TsarS** [LAV45/yii2-translated-behavior#2]
i getting an error "Class 'Locale' not found" when i use site.com/gii/crud/
in D:\OpenServer\domains\site\vendor\lav45\yii2-translated-behavior\src\BaseTranslatedBehavior.php
`$this->language = Locale::getPrimaryLanguage(Yii::$app->language);`

**Comment by LAV45** [comment]
You need to install the library [php5-intl](http://php.net/manual/en/intl.installation.php)

**Comment by LAV45** [comment]
Thank you.
Fix https://github.com/LAV45/yii2-translated-behavior/commit/41899b304bd61fa96a6bcbe7c1cb913fd39de828
