### ISSUE TITLE
Необходима поддержка алиасов для CurrentTranslate

### ISSUE THREAD

**Issue by ilgiz-badamshin** [LAV45/yii2-translated-behavior#3]
Здравствуйте. 
Возникает ошибка при выборке нескольких связей через joinWith с текущим переводом (связь currentTranslate):
> Ambiguous column: 7 ОШИБКА: неоднозначная ссылка на колонку "lang_id". 
```
->joinWith([
    'status.currentTranslate',
    'type.currentTranslate',
])
```
Генерирует такое условие: 
`WHERE ("lang_id"='en-US') AND ("lang_id"='en-US')`
Можно как-то ввести алиасы для currentTranslate для разных моделей?

**Comment by LAV45** [comment]
Спасибо! Поправил.
