### ISSUE TITLE
1.4.2  break BC

### ISSUE THREAD

**Issue by ilgiz-badamshin** [LAV45/yii2-translated-behavior#4]
Problem in class `BaseTranslatedBehavior`. 
I was override class `Lang` and table `{{%lang}}` to use full locale name (en-US, en-GB) instead primary (en).
In 1.4.1 getPrimaryLanguage($locale) used only if $language and $sourceLanguage is null and i can set full locale without problems :
 ```
Yii::$container->set('lav45\translate\TranslatedBehavior', [
            'language' => $app->language,
            'sourceLanguage' => $app->sourceLanguage
        ]);
```

In 1.4.2 `setLanguage` and `setSourceLanguage` always call getPrimaryLanguage($locale). 
Should i override Behavior or you can fix it?

**Comment by LAV45** [comment]
Good afternoon.
how can we reproduce the bug?

**Comment by ilgiz-badamshin** [comment]
I'm not use this feature. 
Selected language is stored in session. In bootstrap i take it from session and set $app->language and call Yii::$container->set('lav45\translate\TranslatedBehavior', ...)

**Comment by ilgiz-badamshin** [comment]
Можно общаться на русском)

**Comment by LAV45** [comment]
В общем пока-что можешь создать свой класс
```php
TranslatedBehavior extends lav45\translate\TranslatedBehavior
{
    public function getPrimaryLanguage($locale)
    {
        return $locale;
    }
}
```

**Comment by LAV45** [comment]
https://github.com/LAV45/yii2-translated-behavior/commit/a3fa375b0c14b94290f2ffd5c4f2e7202311f5fa
```php
Yii::$container->set('lav45\translate\TranslatedBehavior', [
    'primaryLanguage' => function($locale) {
        return strtolower($locale);
    }
]);
```

**Comment by ilgiz-badamshin** [comment]
Спасибо, работает. Может сделать новый релиз 1.4.3 с фиксом?

**Comment by LAV45** [comment]
Добавил.

**Comment by ilgiz-badamshin** [comment]
Спасибо)
