### ISSUE TITLE
Поиск в GridView переводимых строк

### ISSUE THREAD

**Issue by sdelfi** [lav45/yii2-translated-behavior#8]
Приветствую. 

Пара вопросов, которые не смог осилить -
- Возможно ли в GridView при использовании search model 

```
$searchModel = new ServiceSearch();
$dataProvider = $searchModel->search(Yii::$app->request->queryParams);

return $this->render('index', [
    'searchModel' => $searchModel,
    'dataProvider' => $dataProvider,
    'langList' => Lang::getList(),
]);
```
Реализовать поиск и сортировку по переводимым строкам? 
Если да, то как это можно сделать? 

1. Как понимаю, сортировка возможна только в рамках выводимого языка
2. Если возможно реализовать поиск, то как сделать:
2.1 В рамках текущего языка
2.2 В рамках всех языков

- И еще вопрос, как при выводе GridView указать явно язык? Т.е. не тот, который сейчас выбран пользователем/браузером, а определенным, не меняя язык остальных элементов на странице?

Спасибо

P.S. Спасибо за своевременные правки в прошлых issue. Полезный компонент

**Comment by lav45** [comment]
ЗЫ
https://yii2-translated-behavior.lav45.com/admin/post/index
https://github.com/lav45/yii2-translated-behavior-demo/blob/master/backend/models/PostSearch.php
