### ISSUE TITLE
Как указать язык по умолчанию?

### ISSUE THREAD

**Issue by la5erdance** [lav45/yii2-translated-behavior#9]
Добрый день, подскажите как указать язык по умолчанию например немецкий - de, в main.php language не помогает? Спасибо

**Comment by lav45** [comment]
`Yii::$app->sourceLanguage`он устанавливается в `main.php` как и `Yii::$app->language`
```php
return [
    'sourceLanguage' => 'en-US',
    'language' => 'en-US',
// ...
];
```

**Comment by la5erdance** [comment]
Прошу подсказать, я использую Ваш модуль yii2-translated-behavior, у меня есть 2 языка ru-RU и he-IL, мне нужно указать he-IL по умолчанию, я указываю в /frontend/config/main.php - 'sourceLanguage' => 'en-US', 'language' => 'en-US', показал на скриншоте http://dl3.joxi.net/drive/2018/03/10/0014/1813/935701/01/ed5f2b89e7.jpg , а переменная  Yii::$app->language выводит ru, но переменная Yii::$app->sourceLanguage меняется he-IL, я так понимаю что где-то перебивает переменную Yii::$app->language из конфига на ru?

**Comment by lav45** [comment]
Я бы не рекомендовал менять `sourceLanguage`.
Если вам нужно установить язык по умолчанию для всех посетителей вашего сайта, тогда вам нужно сделать следующее:
1) Запретить `ContentNegotiator` автоматически  определять язык на основании заголовков браузера. Для этого в настройках `main.php`
```php
return [
    'components' => [
        'request' => [
            'class' => 'yii\web\Request',
            'acceptableLanguages' => [],
        ],
    ],
];
```
2) Отсортировать массив `\lav45\translate\models\Lang::getLocaleList()` так чтобы нужный вам язык оказался первым в списке. И передать новый массив в `ContentNegotiator` 
```php
class SiteController extends Controller
{
    public function behaviors()
    {
        $locales = Lang::getLocaleList();

        $defaultLocale['he'] = $locales['he'];
        unset($locales['he']);
        $locales = $defaultLocale + $locales;

        return [
            [
                'class' => 'yii\filters\ContentNegotiator',
                'languages' => $locales,
            ]
        ];
    }
}
```

**Comment by lav45** [comment]
Спасибо за интересный вопрос. В ближайшее время доработаю `\lav45\translate\models\Lang` чтобы список языков можно было сортировать из админки.

**Comment by la5erdance** [comment]
Спасибо Вам большое, все работает.
